### ISSUE TITLE
Duplicate trackables created

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#71] opened 2016-06-05 23:50 UTC
I added a new trackable that wasn't in the database. When initially added it was correct, but when I returned to the treatments and summary pages I see three versions of it. When I try to remove one I get endless "please wait, unsaved changes" message. The trackable appears black on the charts and has no dotted line.

![2016-06-05 19_14_54-flaredown](https://cloud.githubusercontent.com/assets/1657444/15809081/bf881764-2b56-11e6-9e85-232566a8265f.png)

**Comment by lmerriam** [comment] 2016-06-07 15:18
Update: on later days (after the day I added it) I see this:

![screenshot 2016-06-07 11 15 57](https://cloud.githubusercontent.com/assets/1657444/15863548/6d537b5e-2ca1-11e6-9eac-8c7d3dba578f.png)

This is interesting because the other spelling of 'mediterrannean' was added on the same day, mistakenly, but didn't show up until the next day. Also the duplicates still show up but _only_ on the day it was added, later days it is singular.

**Comment by algodave** [comment] 2016-06-14 09:01
@lmerriam I tried to replicate this with no success. Can you remember the flow? When you added "mediterranean" for example, do you remember how/when did it change to "Mediterranean Diet"?
What I see in the actual records is just 2 Treatments: "mediterranean" and "Mediterranean Diet".
My feeling is that your connection went down for a bit while saving, so this might be an edge case. Or did you experience a similar issue for other trackables as well?

**Comment by lmerriam** [comment] 2016-06-14 13:29
The flow was that I added 'mediterranean' accidentally, but it didn't appear to go through (didn't show up after I hit enter) so I more carefully typed out "Mediterranean Diet" and added it and when I did it instantly came in as 3 duplicates.

I actually can still see all the duplicates on June 5th (the day I added it) and I cannot see the lowercase version on that day, but every following day I see exactly what you're seeing in the records.

Can you check that day specifically, and maybe there's something I can do on the frontend to debug? Also in the records is there any explanation for why "Mediterranean Diet" has no color ('mediterranean' does have a color).

**Comment by algodave** [comment] 2016-06-14 15:49
@lmerriam I've seen the records for your June 5th checkin and a trackable with the same id (and name "Mediterranean Diet") is present 3 times. I'm going to add a backend validation to prevent such data inconsistency. I still don't have an idea as to how did that happen on the frontend, but it might have been caused by the bug I just fixed in #69

**Comment by algodave** [comment] 2016-06-15 14:47
@lmerriam I've enforced validation to avoid the same trackable twice in the same checkin, and have run a duplicates removal task to drop the existing ones. I've also improved UI feedbeck to users in case of errors on checkin save (see 8adc516)
I would suggest to close this issue and open a new one in case the same bug appears again; we'd also have more logs available then.

**Comment by lmerriam** [comment] 2016-06-15 14:53
Sounds great!

**Comment by algodave** [comment] 2016-06-16 16:04
@lmerriam I've been thinking accidentally about this and I think I've figured out what the root cause is here. I've tried adding "mediterranean" and then "mediterranean diet" and I noticed that "mediterranean" was not suggested to me as I was going to enter "mediterranean diet". 
What happened? By looking at network responses I found that suggestions being returned for "mediterr" include trackables with names that don't appear very similar to the typed string - at least for me as a human. 
As you might remember, we're currently using Postgres' `similarity` function with a `0.1` tolerance value. After a few experiments, I'm realizing that such tolerance value appears to perform well on small substrings, but poorly on longer substrings.
So I would suggest to replace Postgres' `similarity` function with plain-old `ILIKE` operator; another reason to do that is that the `ember-selectize` component applies its own filtering on results, based on text typed, and it uses simple case-insensitive substring matching. So, in case of typos, the frontend logic would hide the expected result, preventing the user from choosing it, even though the backend is actually returning it thanks to the similarity function. 

Similarity function was present in the old app, and that's the main reason why we used it as well. I thought it could help us to deal with typos, but it ends up to be very hard to tune its tolerance param, and also the frontend component turned out to be incompatible with such approach.
So I would suggest to fail back to plain-old `ILIKE` operator. 
What do you think?

/cc @safeforge

**Comment by lmerriam** [comment] 2016-06-16 17:27
It sounds great! We've had some complaints about users struggling to find trackables, so if this fixes the duplicates and improves the autocomplete that's two for one!

**Comment by lmerriam** [comment] 2016-06-16 17:31
@algodave while you're working on that can you possibly help me fix a problem with a tiny copy change in the autocomplete?

Users aren't always realizing that selecting the first option adds whatever you have typed as a trackable. I think we can make that more explicit:

> Add "example treatment"

instead of

> "example treatment"

Make sense?

**Comment by lmerriam** [comment] 2016-06-16 17:59
One more note -- several users have complained that they aren't getting new results when they type in to the autocomplete on android, and I've actually seen it myself. It seems to just filter within the "A" results that start by default. Maybe this will help with that issue?

**Comment by algodave** [comment] 2016-06-16 18:18
@lmerriam I'm not sure I fully understood, but it seems to me that we already have "Add" in the message:

![screen shot 2016-06-16 at 20 14 48](https://cloud.githubusercontent.com/assets/2955556/16128012/3a2b7190-33ff-11e6-8052-5fee8a477116.png)

Also when you say "on android" in the previous comment, do you mean accessing the FD website with the system browser?

**Comment by lmerriam** [comment] 2016-06-16 18:43
You're right! I'm thinking of the old app. Nevermind about the "add" item... I don't know why people aren't understanding that.

I am actually able to replicate the autocomplete thing I mentioned right now, both in Chrome on my android device (it's the default browser) and in the webview app. I will take a video and create a separate ticket, the behavior is fairly complex to describe.

**Comment by algodave** [comment] 2016-06-17 10:56
@lmerriam Try the new autocomplete ;-)

**Comment by algodave** [comment] 2016-06-17 17:17
Reopening in order to implement the following logic discussed with @lmerriam 

```
if chars typed are 3 or less
then return strings ​starting with​ chars typed
else return strings ​containing chars typed
```

**Closed as completed** 2016-06-17 18:09 UTC
